package src.NewFeatures.Records;

import java.math.BigDecimal;

public record Product(String name, BigDecimal price, String type) {
    //By default, the constructor that are generated by compilers are called ad "Canonical Constructors"
    public Product {
        if (name != null && name.isBlank())
            throw new IllegalArgumentException("Name is not valid");

        if(price.compareTo(BigDecimal.ZERO) <= 0)
            throw new IllegalArgumentException("Cost is not valid");
    }

    //Custom Constructor
    public Product(String name, BigDecimal price){
        this(name, price, "Costom");
    }

    public static void main(String[] args){
        Product p = new Product("Iphone", new BigDecimal("99999.99"), "Mobile");
        System.out.print("Product Iphone : " + p);

        //Product c = new Product("",new BigDecimal("99999.99"), "Mobile");
        //Product d = new Product("Iphone",new BigDecimal("-99999.99"), "Mobile");
    }
}
